apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: chatKing
  repository: ''
  version: 0.1.0
  description:
    en_US: chatKing
    zh_Hans: chatKing
  label:
    en_US: chatKing
    zh_Hans: chatKing
  icon: assets/icon.svg
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: chatKing
